export const WebResponses = {

    API_STATUS: {
        UNKNOWN_RESPONSE: "UPE_ERROR_UNKNOWN_RESPONSE",
        ERROR_ACCESSDENIED: "UPE_RESPONSE_API_ERROR_ACCESSDENIED"
    },

    API_LOGOUT_STATUS: {
        LOGOUT_SUCCESSFULLY: "UPE_RESPONSE_API_LOGOUT_SUCCESSFULLY",
        LOGOUT_INVALIDTOKEN: "UPE_RESPONSE_API_LOGOUT_INVALIDTOKEN"
    },

    API_LOGIN_STATUS: {
        LOGIN_INVALIDCPFOREMAIL: "UPE_RESPONSE_API_LOGIN_INVALIDCPFOREMAIL",
        LOGIN_INVALIDPASSWORD: "UPE_RESPONSE_API_LOGIN_INVALIDPASSWORD",
        LOGIN_WRONGCREDENTIALS: "UPE_RESPONSE_API_LOGIN_WRONGCREDENTIALS",
        LOGIN_DEACTIVATEDACCOUNT: "UPE_RESPONSE_API_LOGIN_DEACTIVATEDACCOUNT",
        LOGIN_PENDINGACCEPTANCE: "UPE_RESPONSE_API_LOGIN_PENDINGACCEPTANCE",
        LOGIN_FAILED: "UPE_RESPONSE_API_LOGIN_FAILED",
        LOGIN_SUCCESSFULLY: "UPE_RESPONSE_API_LOGIN_SUCCESSFULLY",
        LOGIN_MISSINGPARAMETERS: "UPE_RESPONSE_API_LOGIN_MISSINGPARAMETERS"
    },
    
    API_REGISTER_STATUS: {
        REGISTER_INVALIDUSERTYPE: "UPE_RESPONSE_API_REGISTER_INVALIDUSERTYPE",
        REGISTER_INVALIDUSERNAME: "UPE_RESPONSE_API_REGISTER_INVALIDUSERNAME",
        REGISTER_INVALIDEMAIL: "UPE_RESPONSE_API_REGISTER_INVALIDEMAIL",
        REGISTER_INVALIDPASSWORD: "UPE_RESPONSE_API_REGISTER_INVALIDPASSWORD",
        REGISTER_INVALIDCPF: "UPE_RESPONSE_API_REGISTER_INVALIDCPF",
        REGISTER_INVALIDCELLPHONE: "UPE_RESPONSE_API_REGISTER_INVALIDCELLPHONE",
        REGISTER_INVALIDCAMPUSID: "UPE_RESPONSE_API_REGISTER_INVALIDCAMPUSID",
        REGISTER_INVALIDCOURSEID: "UPE_RESPONSE_API_REGISTER_INVALIDCOURSEID",
        REGISTER_USERALREADYEXISTS: "UPE_RESPONSE_API_REGISTER_USERALREADYEXISTS",
        REGISTER_FAILED: "UPE_RESPONSE_API_REGISTER_FAILED",
        REGISTER_SUCCESSFULLY: "UPE_RESPONSE_API_REGISTER_SUCCESSFULLY",
        REGISTER_CANNOTCREATEACTIVATION: "UPE_RESPONSE_API_REGISTER_CANNOTCREATEACTIVATION",
        REGISTER_MISSINGPARAMETERS: "UPE_RESPONSE_API_REGISTER_MISSINGPARAMETERS"
    },

    API_FORGOTPASSWORD_STATUS: {
        FORGOTPASSWORD_INVALIDCPFOREMAIL: "UPE_RESPONSE_API_FORGOTPASSWORD_INVALIDCPFOREMAIL",
        FORGOTPASSWORD_FAILED: "UPE_RESPONSE_API_FORGOTPASSWORD_FAILED",
        FORGOTPASSWORD_PENDINGACCEPTANCE: "UPE_RESPONSE_API_FORGOTPASSWORD_PENDINGACCEPTANCE",
        FORGOTPASSWORD_DEACTIVATEDACCOUNT: "UPE_RESPONSE_API_FORGOTPASSWORD_DEACTIVATEDACCOUNT",
        FORGOTPASSWORD_SUCCESSFULLY: "UPE_RESPONSE_API_FORGOTPASSWORD_SUCCESSFULLY",
        FORGOTPASSWORD_MISSINGPARAMETERS: "UPE_RESPONSE_API_FORGOTPASSWORD_MISSINGPARAMETERS"
    },

    API_LISTCAMPUS_STATUS: {
        LISTCAMPUS_SUCCESSFULLY: "UPE_RESPONSE_API_LISTCAMPUS_SUCCESSFULLY",
        LISTCAMPUS_ERROR: "UPE_RESPONSE_API_LISTCAMPUS_ERROR"
    },

    API_LISTCOURSES_STATUS: {
        LISTCOURSES_SUCCESSFULLY: "UPE_RESPONSE_API_LISTCOURSES_SUCCESSFULLY",
        LISTCOURSES_ERROR: "UPE_RESPONSE_API_LISTCOURSES_ERROR",
        LISTCOURSES_INVALIDCOURSEASSOCIATION: "UPE_RESPONSE_API_LISTCOURSES_INVALIDCOURSEASSOCIATION"
    },

    /* API DE GESTORES */

    API_LISTPENDINGUSERS_STATUS: {
        LISTPENDINGUSERS_INVALIDTOKEN: "UPE_RESPONSE_API_LISTPENDINGUSERS_INVALIDTOKEN",
        LISTPENDINGUSERS_SUCCESSFULLY: "UPE_RESPONSE_API_LISTPENDINGUSERS_SUCCESSFULLY"
    },

    API_ACCEPTUSER_STATUS: {
        ACCEPTUSER_SUCCESSFULLY: "UPE_RESPONSE_API_ACCEPTUSER_SUCCESSFULLY",
        ACCEPTUSER_INVALIDUSERID: "UPE_RESPONSE_API_ACCEPTUSER_INVALIDUSERID",
        ACCEPTUSER_INVALIDTOKEN: "UPE_RESPONSE_API_ACCEPTUSER_INVALIDTOKEN",
        ACCEPTUSER_FAILED: "UPE_RESPONSE_API_ACCEPTUSER_FAILED"
    },

    API_REJECTUSER_STATUS: {
        REJECTUSER_SUCCESSFULLY: "UPE_RESPONSE_API_REJECTUSER_SUCCESSFULLY",
        REJECTUSER_INVALIDUSERID: "UPE_RESPONSE_API_REJECTUSER_INVALIDUSERID",
        REJECTUSER_INVALIDTOKEN: "UPE_RESPONSE_API_REJECTUSER_INVALIDTOKEN",
        REJECTUSER_FAILED: "UPE_RESPONSE_API_REJECTUSER_FAILED"
    },

    API_VALIDATEQRCODE_STATUS: {
        VALIDATEQRCODE_INVALIDTOKEN: "UPE_RESPONSE_API_VALIDATEQRCODE_INVALIDTOKEN",
        VALIDATEQRCODE_INVALIDQRCODE: "UPE_RESPONSE_API_VALIDATEQRCODE_INVALIDQRCODE",
        VALIDATEQRCODE_SUCCESSFULLY: "UPE_RESPONSE_API_VALIDATEQRCODE_SUCCESSFULLY"
    },

    API_SEARCHUSERS_STATUS: {
        SEARCHUSERS_INVALIDTOKEN: "UPE_RESPONSE_API_SEARCHUSERS_INVALIDTOKEN",
        SEARCHUSERS_NOMATCHFOUND: "UPE_RESPONSE_API_SEARCHUSERS_NOMATCHFOUND",
        SEARCHUSERS_SUCCESSFULLY: "UPE_RESPONSE_API_SEARCHUSERS_SUCCESSFULLY"
    },

    API_DETAILUSER_STATUS: {
        DETAILUSER_INVALIDTOKEN: "UPE_RESPONSE_API_DETAILUSER_INVALIDTOKEN",
        DETAILUSER_INVALIDUSERID: "UPE_RESPONSE_API_DETAILUSER_INVALIDUSERID",
        DETAILUSER_SUCCESSFULLY: "UPE_RESPONSE_API_DETAILUSER_SUCCESSFULLY"
    },

    API_DELETEUSER_STATUS: {
        DELETEUSER_INVALIDTOKEN: "UPE_RESPONSE_API_DELETEUSER_INVALIDTOKEN",
        DELETEUSER_INVALIDUSERID: "UPE_RESPONSE_API_DELETEUSER_INVALIDUSERID",
        DELETEUSER_SUCCESSFULLY: "UPE_RESPONSE_API_DELETEUSER_SUCCESSFULLY"
    },

    API_SEARCHLOCAL_STATUS: {
        SEARCHLOCAL_INVALIDTOKEN: "UPE_RESPONSE_API_SEARCHLOCAL_INVALIDTOKEN",
        SEARCHLOCAL_NOMATCHFOUND: "UPE_RESPONSE_API_SEARCHLOCAL_NOMATCHFOUND",
        SEARCHLOCAL_SUCCESSFULLY: "UPE_RESPONSE_API_SEARCHLOCAL_SUCCESSFULLY"
    },

    API_DETAILLOCAL_STATUS: {
        DETAILLOCAL_INVALIDTOKEN: "UPE_RESPONSE_API_DETAILLOCAL_INVALIDTOKEN",
        DETAILLOCAL_INVALIDLOCALID: "UPE_RESPONSE_API_DETAILLOCAL_INVALIDLOCALID",
        DETAILLOCAL_SUCCESSFULLY: "UPE_RESPONSE_API_DETAILLOCAL_SUCCESSFULLY"
    },

    API_DELETELOCAL_STATUS: {
        DELETELOCAL_INVALIDTOKEN: "UPE_RESPONSE_API_DELETELOCAL_INVALIDTOKEN",
        DELETELOCAL_INVALIDLOCALID: "UPE_RESPONSE_API_DELETELOCAL_INVALIDLOCALID",
        DELETELOCAL_SUCCESSFULLY: "UPE_RESPONSE_API_DELETELOCAL_SUCCESSFULLY"
    },

    API_DETAILRESERVE_STATUS: {
        DETAILRESERVE_INVALIDTOKEN: "UPE_RESPONSE_API_DETAILRESERVE_INVALIDTOKEN",
        DETAILRESERVE_INVALIDRESERVEID: "UPE_RESPONSE_API_DETAILRESERVE_INVALIDRESERVEID",
        DETAILRESERVE_SUCCESSFULLY: "UPE_RESPONSE_API_DETAILRESERVE_SUCCESSFULLY"
    },

    API_DELETERESERVE_STATUS: {
        DELETERESERVE_INVALIDTOKEN: "UPE_RESPONSE_API_DELETERESERVE_INVALIDTOKEN",
        DELETERESERVE_INVALIDRESERVEID: "UPE_RESPONSE_API_DELETERESERVE_INVALIDRESERVEID",
        DELETERESERVE_SUCCESSFULLY: "UPE_RESPONSE_API_DELETERESERVE_SUCCESSFULLY"
    },

    API_LISTCAMPUSMESSAGES_STATUS: {
        LISTCAMPUSMESSAGES_INVALIDTOKEN: "UPE_RESPONSE_API_LISTCAMPUSMESSAGES_INVALIDTOKEN",
        LISTCAMPUSMESSAGES_EMPTYMESSAGES: "UPE_RESPONSE_API_LISTCAMPUSMESSAGES_EMPTYMESSAGES",
        LISTCAMPUSMESSAGES_SUCCESSFULLY: "UPE_RESPONSE_API_LISTCAMPUSMESSAGES_SUCCESSFULLY"
    },

    API_CREATECAMPUSMESSAGE_STATUS: {
        CREATECAMPUSMESSAGE_INVALIDTOKEN: "UPE_RESPONSE_API_CREATECAMPUSMESSAGE_INVALIDTOKEN",
        CREATECAMPUSMESSAGE_MISSINGPARAMETERS: "UPE_RESPONSE_API_CREATECAMPUSMESSAGE_MISSINGPARAMETERS",
        CREATECAMPUSMESSAGE_FAILED: "UPE_RESPONSE_API_CREATECAMPUSMESSAGE_FAILED",
        CREATECAMPUSMESSAGE_SUCCESSFULLY: "UPE_RESPONSE_API_CREATECAMPUSMESSAGE_SUCCESSFULLY"
    },

    API_DELETECAMPUSMESSAGE_STATUS: {
        DELETECAMPUSMESSAGE_INVALIDTOKEN: "UPE_RESPONSE_API_DELETECAMPUSMESSAGE_INVALIDTOKEN",
        DELETECAMPUSMESSAGE_INVALIDMESSAGEID: "UPE_RESPONSE_API_DELETECAMPUSMESSAGE_INVALIDMESSAGEID",
        DELETECAMPUSMESSAGE_FAILED: "UPE_RESPONSE_API_DELETECAMPUSMESSAGE_FAILED",
        DELETECAMPUSMESSAGE_SUCCESSFULLY: "UPE_RESPONSE_API_DELETECAMPUSMESSAGE_SUCCESSFULLY"
    }

};
