export const WebResponses = {

    UNKNOWN_API_STATUS: {
        UNKNOWN_RESPONSE: "UPE_ERROR_UNKNOWN_RESPONSE",
        ERROR_ACCESSDENIED: "UPE_RESPONSE_API_ERROR_ACCESSDENIED"
    },

    API_LOGOUT_STATUS: {
        LOGOUT_SUCCESSFULLY: "UPE_RESPONSE_API_LOGOUT_SUCCESSFULLY",
        LOGOUT_INVALIDTOKEN: "UPE_RESPONSE_API_LOGOUT_INVALIDTOKEN"
    },

    API_LOGIN_STATUS: {
        LOGIN_INVALIDCPFOREMAIL: "UPE_RESPONSE_API_LOGIN_INVALIDCPFOREMAIL",
        LOGIN_INVALIDPASSWORD: "UPE_RESPONSE_API_LOGIN_INVALIDPASSWORD",
        LOGIN_WRONGCREDENTIALS: "UPE_RESPONSE_API_LOGIN_WRONGCREDENTIALS",
        LOGIN_DEACTIVATEDACCOUNT: "UPE_RESPONSE_API_LOGIN_DEACTIVATEDACCOUNT",
        LOGIN_PENDINGACCEPTANCE: "UPE_RESPONSE_API_LOGIN_PENDINGACCEPTANCE",
        LOGIN_FAILED: "UPE_RESPONSE_API_LOGIN_FAILED",
        LOGIN_SUCCESSFULLY: "UPE_RESPONSE_API_LOGIN_SUCCESSFULLY",
        LOGIN_MISSINGPARAMETERS: "UPE_RESPONSE_API_LOGIN_MISSINGPARAMETERS"
    },
    
    API_REGISTER_STATUS: {
        REGISTER_INVALIDUSERTYPE: "UPE_RESPONSE_API_REGISTER_INVALIDUSERTYPE",
        REGISTER_INVALIDUSERNAME: "UPE_RESPONSE_API_REGISTER_INVALIDUSERNAME",
        REGISTER_INVALIDEMAIL: "UPE_RESPONSE_API_REGISTER_INVALIDEMAIL",
        REGISTER_INVALIDPASSWORD: "UPE_RESPONSE_API_REGISTER_INVALIDPASSWORD",
        REGISTER_INVALIDCPF: "UPE_RESPONSE_API_REGISTER_INVALIDCPF",
        REGISTER_INVALIDCELLPHONE: "UPE_RESPONSE_API_REGISTER_INVALIDCELLPHONE",
        REGISTER_INVALIDCAMPUSID: "UPE_RESPONSE_API_REGISTER_INVALIDCAMPUSID",
        REGISTER_INVALIDCOURSEID: "UPE_RESPONSE_API_REGISTER_INVALIDCOURSEID",
        REGISTER_USERALREADYEXISTS: "UPE_RESPONSE_API_REGISTER_USERALREADYEXISTS",
        REGISTER_FAILED: "UPE_RESPONSE_API_REGISTER_FAILED",
        REGISTER_SUCCESSFULLY: "UPE_RESPONSE_API_REGISTER_SUCCESSFULLY",
        REGISTER_CANNOTCREATEACTIVATION: "UPE_RESPONSE_API_REGISTER_CANNOTCREATEACTIVATION",
        REGISTER_MISSINGPARAMETERS: "UPE_RESPONSE_API_REGISTER_MISSINGPARAMETERS"
    },

    API_FORGOTPASSWORD_STATUS: {
        FORGOTPASSWORD_INVALIDCPFOREMAIL: "UPE_RESPONSE_API_FORGOTPASSWORD_INVALIDCPFOREMAIL",
        FORGOTPASSWORD_FAILED: "UPE_RESPONSE_API_FORGOTPASSWORD_FAILED",
        FORGOTPASSWORD_PENDINGACCEPTANCE: "UPE_RESPONSE_API_FORGOTPASSWORD_PENDINGACCEPTANCE",
        FORGOTPASSWORD_DEACTIVATEDACCOUNT: "UPE_RESPONSE_API_FORGOTPASSWORD_DEACTIVATEDACCOUNT",
        FORGOTPASSWORD_SUCCESSFULLY: "UPE_RESPONSE_API_FORGOTPASSWORD_SUCCESSFULLY",
        FORGOTPASSWORD_MISSINGPARAMETERS: "UPE_RESPONSE_API_FORGOTPASSWORD_MISSINGPARAMETERS"
    },

    API_LISTCAMPUS_STATUS: {
        LISTCAMPUS_SUCCESSFULLY: "UPE_RESPONSE_API_LISTCAMPUS_SUCCESSFULLY"
    },

    API_LISTCOURSES_STATUS: {
        LISTCOURSES_SUCCESSFULLY: "UPE_RESPONSE_API_LISTCOURSES_SUCCESSFULLY"
    },

    /* API DE GESTORES */

    API_LISTPENDINGUSERS_STATUS: {
        LISTPENDINGUSERS_INVALIDTOKEN: "UPE_RESPONSE_API_LISTPENDINGUSERS_INVALIDTOKEN",
        LISTPENDINGUSERS_SUCCESSFULLY: "UPE_RESPONSE_API_LISTPENDINGUSERS_SUCCESSFULLY"
    },

    API_ACCEPTUSER_STATUS: {
        ACCEPTUSER_SUCCESSFULLY: "UPE_RESPONSE_API_ACCEPTUSER_SUCCESSFULLY",
        ACCEPTUSER_INVALIDUSERID: "UPE_RESPONSE_API_ACCEPTUSER_INVALIDUSERID",
        ACCEPTUSER_INVALIDTOKEN: "UPE_RESPONSE_API_ACCEPTUSER_INVALIDTOKEN",
        ACCEPTUSER_FAILED: "UPE_RESPONSE_API_ACCEPTUSER_FAILED",

    },

    API_REJECTUSER_STATUS: {
        REJECTUSER_SUCCESSFULLY: "UPE_RESPONSE_API_REJECTUSER_SUCCESSFULLY",
        REJECTUSER_INVALIDUSERID: "UPE_RESPONSE_API_REJECTUSER_INVALIDUSERID",
        REJECTUSER_INVALIDTOKEN: "UPE_RESPONSE_API_REJECTUSER_INVALIDTOKEN",
        REJECTUSER_FAILED: "UPE_RESPONSE_API_REJECTUSER_FAILED"
    }

};
